<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>OeXYZ.Core</AssemblyName>
    <RootNamespace>OeXYZ.Core</RootNamespace>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="OeXYZ.Core.Tests" />
  </ItemGroup>
</Project>
